---
# ddclient/tasks/main.yml

- name: Clone DDClient's Git Repo
  git:
    repo: "{{ ddclient_git_repo_http }}"
    dest: "{{ ddclient_git_repo_dest }}"
    update: yes
    accept_hostkey: yes
  register: _ddclient_git_cloned

- import_tasks: install.yml

- name: Build Out ddclient.conf File
  template:
    src: ddclient.conf.j2
    dest: /etc/ddclient/ddclient.conf
    owner: root
    group: root
  become: true
  notify: Restart DDClient

- name: Make All The Files Executable
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    state: file
  with_items:
    - { path: "/etc/init.d/ddclient", mode: "0750" }
    - { path: "/etc/ddclient/ddclient.conf", mode: "0700" }
    - { path: "/usr/sbin/ddclient", mode: "0775" }
  become: true
